# Generated by Django 3.0.3 on 2020-02-24 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_add_project_default_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='facilitators',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_facilitator': True}, related_name='facilitates_projects', related_query_name='facilitates_project', to=settings.AUTH_USER_MODEL, verbose_name='facilitators'),
        ),
    ]
