# Generated by Django 3.0.3 on 2020-02-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_project_default_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dataflow_hierarchy',
            field=models.FileField(blank=True, null=True, upload_to='projects/dataflows', verbose_name='Dataflow hierarchy'),
        ),
    ]
