# Generated by Django 3.0.3 on 2020-03-05 06:41

import core.fields
from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_add_project_facilitators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='countries',
            field=core.fields.ChoiceArrayField(base_field=django_countries.fields.CountryField(max_length=2), blank=True, default=list, size=None, verbose_name='countries'),
        ),
    ]
