# Generated by Django 3.0.3 on 2020-03-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200305_0941'),
        ('projects', '0005_allow_countries_choices_on_project'),
    ]

    operations = [
    ]
