# Generated by Django 3.0.3 on 2020-03-11 21:25

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_auto_20200311_2125'),
        ('surveys', '0036_auto_20200311_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='extras')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_respondents', related_query_name='created_respondent', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respondents', related_query_name='respondent', to='users.Gender', verbose_name='gender')),
                ('hierarchy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respondents', related_query_name='respondent', to='surveys.DataflowHierarchy', verbose_name='hierarchy')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondents', related_query_name='respondent', to='surveys.Survey', verbose_name='survey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respondents', related_query_name='respondent', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Respondent',
                'verbose_name_plural': 'Respondents',
                'ordering': ['-created_at'],
            },
        ),
    ]
