# Generated by Django 3.0.3 on 2020-03-16 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0038_add_survey_genders'),
        ('respondents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respondents', related_query_name='respondent', to='surveys.Role', verbose_name='role'),
        ),
    ]
