# Generated by Django 3.0.3 on 2020-03-18 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0049_remove_field_hierachy_from_role'),
        ('respondents', '0002_add_respondent_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='hierarchy_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respondents', related_query_name='respondent', to='surveys.HierarchyLevel', verbose_name='hierarchy level'),
        ),
    ]
