# Generated by Django 3.0.3 on 2020-03-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0003_add_field_hierachy_level_to_respondent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondent',
            name='hierarchy',
        ),
    ]
