# Generated by Django 3.0.3 on 2020-03-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0051_remove_field_hierachy_from_entity'),
        ('respondents', '0004_remove_field_hierachy_from_respondent'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='hierarchy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respondents', related_query_name='respondent', to='surveys.DataflowHierarchy', verbose_name='hierarchy'),
        ),
    ]
