# Generated by Django 3.0.3 on 2020-03-22 14:59

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('respondents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='extras')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', related_query_name='response', to='surveys.Dataset', verbose_name='dataset')),
                ('dataset_frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', related_query_name='response', to='surveys.DatasetFrequency', verbose_name='frequency')),
            ],
            options={
                'verbose_name': 'Dataset Response',
                'verbose_name_plural': 'Dataset Responses',
            },
        ),
        migrations.CreateModel(
            name='DatasetTopicResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='extras')),
                ('dataset_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_responses', related_query_name='topic_response', to='responses.DatasetResponse', verbose_name='dataset response')),
                ('percieved_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='percieved_owns_datasets', related_query_name='percieved_owns_dataset', to='surveys.Role', verbose_name='perceived owner')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_responses', related_query_name='dataset_response', to='surveys.Topic', verbose_name='topic')),
            ],
            options={
                'verbose_name': 'Dataset Topic Response',
                'verbose_name_plural': 'Dataset Topic Responses',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('consented_at', models.DateTimeField(blank=True, null=True, verbose_name='consented at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='extras')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_responses', related_query_name='created_response', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', related_query_name='response', to='respondents.Respondent', verbose_name='respondent')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', related_query_name='response', to='surveys.Survey', verbose_name='survey')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='data')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='extras')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', related_query_name='response', to='surveys.Question', verbose_name='survey')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', related_query_name='question_response', to='responses.SurveyResponse', verbose_name='response')),
            ],
            options={
                'verbose_name': 'Question Response',
                'verbose_name_plural': 'Question Responses',
            },
        ),
        migrations.CreateModel(
            name='DatasetTopicStorageAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_topic_responses', related_query_name='dataset_topic_response', to='surveys.DatasetAccess', verbose_name='dataset access')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', related_query_name='storage', to='responses.DatasetTopicResponse', verbose_name='dataset topic storage')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_topic_responses', related_query_name='dataset_topic_response', to='surveys.DatasetStorage', verbose_name='dataset storage')),
            ],
            options={
                'verbose_name': 'Dataset Response Storage Access',
                'verbose_name_plural': 'Dataset Response Storage Access',
            },
        ),
        migrations.CreateModel(
            name='DatasetTopicShared',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('dataset_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responses.DatasetResponse', verbose_name='dataset response')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Entity', verbose_name='entity')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Topic', verbose_name='topic')),
            ],
            options={
                'verbose_name': 'Dataset Topic Shared',
                'verbose_name_plural': 'Dataset Topics Shared',
            },
        ),
        migrations.CreateModel(
            name='DatasetTopicReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('dataset_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responses.DatasetResponse', verbose_name='dataset response')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Entity', verbose_name='entity')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Topic', verbose_name='topic')),
            ],
            options={
                'verbose_name': 'Dataset Topic Received',
                'verbose_name_plural': 'Dataset Topics Received',
            },
        ),
        migrations.AddField(
            model_name='datasetresponse',
            name='received_from',
            field=models.ManyToManyField(related_name='dataset_responses_received_from', related_query_name='dataset_response_received_from', through='responses.DatasetTopicReceived', to='surveys.Entity', verbose_name='received from'),
        ),
        migrations.AddField(
            model_name='datasetresponse',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_responses', related_query_name='dataset_response', to='responses.SurveyResponse', verbose_name='response'),
        ),
        migrations.AddField(
            model_name='datasetresponse',
            name='shared_to',
            field=models.ManyToManyField(related_name='dataset_responses_shared_to', related_query_name='dataset_response_shared_to', through='responses.DatasetTopicShared', to='surveys.Entity', verbose_name='shared to'),
        ),
    ]
