# Generated by Django 3.0.3 on 2020-02-12 20:16

import uuid

from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    User = apps.get_model('users', 'User')

    objects = []

    for user in User.objects.iterator():
        user.uuid = uuid.uuid4()
        objects.append(user)

    User.objects.bulk_update(objects, ['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_country_phone_number'),
    ]

    # add field
    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(editable=False, null=True, verbose_name='UUID'),
        ),

        # populate UUID
        migrations.RunPython(
            gen_uuid, reverse_code=migrations.RunPython.noop
        ),

        # set UUID field
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
