# Generated by Django 3.0.3 on 2020-02-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_facilitator',
            field=models.BooleanField(default=False, verbose_name='is facilitator'),
        ),
    ]
