# Generated by Django 3.0.3 on 2020-02-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_facilitator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_respondent',
            field=models.BooleanField(default=False, verbose_name='is respondent'),
        ),
    ]
