# Generated by Django 3.0.3 on 2020-03-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200311_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='is_primary',
            field=models.BooleanField(blank=True, default=False, help_text='Shared system wide. Not for specific project or survey only.', verbose_name='is primary'),
        ),
    ]
