# Generated by Django 3.0.3 on 2020-03-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_gender_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='code',
            field=models.SlugField(blank=True, max_length=255, verbose_name='code'),
        ),
    ]
