# Generated by Django 3.0.3 on 2020-03-17 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_gender_is_primary'),
        ('users', '0009_auto_20200312_1001'),
    ]

    operations = [
    ]
