# Generated by Django 3.0.3 on 2020-03-21 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_gender_code_unique_constrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_primary': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', related_query_name='user', to='users.Gender', verbose_name='gender'),
        ),
    ]
