# Generated by Django 3.0.3 on 2020-02-10 13:16

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_add_organization_related_query_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='display name')),
                ('learning_enquiry', models.CharField(max_length=255, verbose_name='learning enquiry')),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), blank=True, default=list, size=None, verbose_name='languages')),
                ('code', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='code')),
                ('login_required', models.BooleanField(blank=True, default=True, help_text='Do you want users to login before responding to the survey?', verbose_name='login required')),
                ('respondent_can_aggregate', models.BooleanField(blank=True, default=True, help_text="Do you want repondents to see visualizations or aggregates of other users' responses?", verbose_name='respondent can aggregate')),
                ('respondent_can_invite', models.BooleanField(blank=True, default=True, help_text='Do you want users to share email addresses of other potential respondents?', verbose_name='respondent can suggest others')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Is published', verbose_name='is active')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='extras')),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', related_query_name='created_survey', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', related_query_name='survey', to='projects.Project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
            },
        ),
    ]
