# Generated by Django 3.0.3 on 2020-02-11 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_project_add_organization_related_query_name'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataflowHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('level_name', models.CharField(max_length=128, unique=True, verbose_name='level name')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_dataflow_hierarchy', related_query_name='created_dataflow_hierarchies', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='surveys.DataflowHierarchy', verbose_name='parent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchies', related_query_name='hierarchy', to='projects.Project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'Dataflow Hierarchy',
                'verbose_name_plural': 'Dataflow Hierarchies',
            },
        ),
    ]
