# Generated by Django 3.0.3 on 2020-02-11 16:27

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0006_questiongroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.SlugField(blank=True, verbose_name='field name')),
                ('label', models.CharField(help_text='this will be displayed to user', max_length=255, verbose_name='label')),
                ('type', models.CharField(choices=[('integer', 'integer'), ('decimal', 'decimal'), ('text', 'text'), ('select_one', 'select one'), ('select_multiple', 'select multiple'), ('date', 'date'), ('time', 'time'), ('dateTime', 'date & time'), ('image', 'image'), ('file', 'file')], max_length=50, verbose_name='type')),
                ('options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='options')),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_questions', related_query_name='created_question', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', related_query_name='question', to='surveys.QuestionGroup', verbose_name='group')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', related_query_name='question', to='surveys.Survey', verbose_name='survey')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'unique_together': {('survey', 'name')},
            },
        ),
    ]
