# Generated by Django 3.0.3 on 2020-02-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='learning_enquiry',
        ),
        migrations.AddField(
            model_name='survey',
            name='research_question',
            field=models.CharField(default='-', max_length=255, verbose_name='research question'),
            preserve_default=False,
        ),
    ]
