# Generated by Django 3.0.3 on 2020-02-11 18:45

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0010_respondent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='extras')),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_responses', related_query_name='created_response', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', related_query_name='response', to='surveys.Respondent', verbose_name='respondent')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', related_query_name='response', to='surveys.Survey', verbose_name='survey')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
            },
        ),
    ]
