# Generated by Django 3.0.3 on 2020-02-11 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_dataflowhierarchy_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
    ]
