# Generated by Django 3.0.3 on 2020-02-19 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_correct_role_verbose_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created_at'], 'verbose_name': 'Survey', 'verbose_name_plural': 'Surveys'},
        ),
    ]
