# Generated by Django 3.0.3 on 2020-02-17 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_gender'),
        ('surveys', '0014_correct_role_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respondents', related_query_name='respondent', to='users.Gender', verbose_name='gender'),
        ),
    ]
