# Generated by Django 3.0.3 on 2020-02-18 12:48

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0015_respondent_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_access', related_query_name='dataset_access', to='surveys.Survey', verbose_name='survey')),
            ],
            options={
                'verbose_name': 'Dataset Access',
                'verbose_name_plural': 'Dataset Access',
            },
        ),
        migrations.CreateModel(
            name='DatasetFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, verbose_name='frequency')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_frequencies', related_query_name='dataset_frequency', to='surveys.Survey', verbose_name='survey')),
            ],
            options={
                'verbose_name': 'Dataset frequency',
                'verbose_name_plural': 'Dataset Frequencies',
            },
        ),
        migrations.CreateModel(
            name='DatasetResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='extras')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', related_query_name='response', to='surveys.Dataset', verbose_name='dataset')),
                ('dataset_frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', related_query_name='response', to='surveys.DatasetFrequency', verbose_name='frequency')),
            ],
            options={
                'verbose_name': 'Dataset Response',
                'verbose_name_plural': 'Dataset Responses',
            },
        ),
        migrations.CreateModel(
            name='DatasetStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_storages', related_query_name='dataset_storage', to='surveys.Survey', verbose_name='survey')),
            ],
            options={
                'verbose_name': 'Dataset Storage',
                'verbose_name_plural': 'Dataset Storage',
            },
        ),
        migrations.CreateModel(
            name='DatasetTopicResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='extras')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_responses', related_query_name='topic_response', to='surveys.Dataset', verbose_name='dataset')),
            ],
            options={
                'verbose_name': 'Dataset Topic Response',
                'verbose_name_plural': 'Dataset Topic Responses',
            },
        ),
        migrations.AlterField(
            model_name='respondent',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_respondents', related_query_name='created_respondent', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='response',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_responses', related_query_name='created_response', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='extras')),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_survey_entities', related_query_name='created_survey_entity', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('hierarchy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', related_query_name='entity', to='surveys.DataflowHierarchy', verbose_name='hierarchy')),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
            },
        ),
        migrations.CreateModel(
            name='DatasetTopicStorageAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.DatasetAccess', verbose_name='dataset access')),
                ('dataset_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.DatasetTopicResponse', verbose_name='dataset topic storage')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.DatasetStorage', verbose_name='dataset storage')),
            ],
            options={
                'verbose_name': 'Dataset Response Storage Access',
                'verbose_name_plural': 'Dataset Response Storage Access',
            },
        ),
        migrations.CreateModel(
            name='DatasetTopicShared',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('dataset_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.DatasetResponse', verbose_name='dataset response')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Entity', verbose_name='entity')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Topic', verbose_name='topic')),
            ],
            options={
                'verbose_name': 'Dataset Topic Shared',
                'verbose_name_plural': 'Dataset Topics Shared',
            },
        ),
        migrations.AddField(
            model_name='datasettopicresponse',
            name='dataset_storages',
            field=models.ManyToManyField(related_name='dataset_responses', related_query_name='dataset_response', through='surveys.DatasetTopicStorageAccess', to='surveys.DatasetStorage', verbose_name='dataset storages'),
        ),
        migrations.AddField(
            model_name='datasettopicresponse',
            name='percieved_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percieved_owns_datasets', related_query_name='percieved_owns_dataset', to='surveys.Role', verbose_name='perceived owner'),
        ),
        migrations.AddField(
            model_name='datasettopicresponse',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_topic_responses', related_query_name='dataset_topic_response', to='surveys.Response', verbose_name='response'),
        ),
        migrations.AddField(
            model_name='datasettopicresponse',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_responses', related_query_name='dataset_response', to='surveys.Topic', verbose_name='topic'),
        ),
        migrations.CreateModel(
            name='DatasetTopicReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('dataset_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.DatasetResponse', verbose_name='dataset response')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Entity', verbose_name='entity')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Topic', verbose_name='topic')),
            ],
            options={
                'verbose_name': 'Dataset Topic Received',
                'verbose_name_plural': 'Dataset Topics Received',
            },
        ),
        migrations.AddField(
            model_name='datasetresponse',
            name='received_from',
            field=models.ManyToManyField(related_name='dataset_responses_received_from', related_query_name='dataset_response_received_from', through='surveys.DatasetTopicReceived', to='surveys.Entity', verbose_name='received from'),
        ),
        migrations.AddField(
            model_name='datasetresponse',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_responses', related_query_name='dataset_response', to='surveys.Response', verbose_name='response'),
        ),
        migrations.AddField(
            model_name='datasetresponse',
            name='shared_to',
            field=models.ManyToManyField(related_name='dataset_responses_shared_to', related_query_name='dataset_response_shared_to', through='surveys.DatasetTopicShared', to='surveys.Entity', verbose_name='shared to'),
        ),
    ]
