# Generated by Django 3.0.3 on 2020-02-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_survey_invitation_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataflowhierarchy',
            name='level_name',
            field=models.CharField(max_length=128, verbose_name='level name'),
        ),
    ]
