# Generated by Django 3.0.3 on 2020-02-19 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_add_organization_related_query_name'),
        ('surveys', '0018_dataflowhierarchy_level_name_remove_unique_constrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataflowhierarchy',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='hierarchies', related_query_name='hierarchy', to='projects.Project', verbose_name='project'),
        ),
    ]
