# Generated by Django 3.0.3 on 2020-02-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_dataflowhierarchy_project_allow_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='consented_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='consented at'),
        ),
    ]
