# Generated by Django 3.0.3 on 2020-02-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0023_datasetresponse_dataset_frequency_remove_null_constrain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['created_at'], 'verbose_name': 'Survey', 'verbose_name_plural': 'Surveys'},
        ),
    ]
