# Generated by Django 3.0.3 on 2020-02-22 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0025_link_datasettopicresponse_to_dataset_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasettopicresponse',
            name='dataset_storages',
            field=models.ManyToManyField(blank=True, related_name='dataset_responses', related_query_name='dataset_response', through='surveys.DatasetTopicStorageAccess', to='surveys.DatasetStorage', verbose_name='dataset storages'),
        ),
        migrations.AlterField(
            model_name='datasettopicresponse',
            name='percieved_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='percieved_owns_datasets', related_query_name='percieved_owns_dataset', to='surveys.Role', verbose_name='perceived owner'),
        ),
    ]
