# Generated by Django 3.0.3 on 2020-02-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0028_remove_dataset_storages_from_datasettopicresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completed at'),
        ),
    ]
