# Generated by Django 3.0.3 on 2020-03-05 07:01

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0031_dataflow_hierarchy_remove_name_unique_constrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='display_name',
            field=models.CharField(blank=True, help_text='Use this optional field to provide the survey name as Respondents will see it.', max_length=255, verbose_name='alternative name'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='languages',
            field=core.fields.ChoiceArrayField(base_field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], max_length=5), size=None, verbose_name='languages'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='research_question',
            field=models.CharField(help_text='Every Data Compass survey must have a specific research question. What is yours?', max_length=255, verbose_name='research question'),
        ),
    ]
