# Generated by Django 3.0.3 on 2020-03-05 06:41

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0031_dataflow_hierarchy_remove_name_unique_constrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='allow_respondent_topics',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='If Yes, respondents will be able to add their own topics.', verbose_name='allow respondent topics'),
        ),
        migrations.AddField(
            model_name='survey',
            name='respondent_topic_number',
            field=models.IntegerField(default=10, help_text='Up to 10 topics are allowed', verbose_name='respondent topic number'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='display_name',
            field=models.CharField(blank=True, help_text='Use this optional field to provide the survey name as Respondents will see it.', max_length=255, verbose_name='alternative name'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='languages',
            field=core.fields.ChoiceArrayField(base_field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], max_length=5), size=None, verbose_name='languages'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='login_required',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text="If no, they won't be able to save and return to their results, or view previous results.", verbose_name='login required'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='research_question',
            field=models.CharField(help_text='Every Data Compass survey must have a specific research question. What is yours?', max_length=255, verbose_name='research question'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='respondent_can_aggregate',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text="'Yes', will update their networ visual with all users' responses in realtime. 'No' will not.", verbose_name='respondent can aggregate'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='respondent_can_invite',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='If Yes, the survey will include question collecting email address. Respondents are responsible for ensuring consent.', verbose_name='respondent can suggest others'),
        ),
    ]
