# Generated by Django 3.0.3 on 2020-03-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0032_alter_help_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respondent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Respondent', 'verbose_name_plural': 'Respondents'},
        ),
    ]
