# Generated by Django 3.0.3 on 2020-03-05 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0032_auto_20200305_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='respondent_topic_number',
            field=models.PositiveSmallIntegerField(default=10, help_text='Up to 10 topics are allowed', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='respondent topic number'),
        ),
    ]
