# Generated by Django 3.0.3 on 2020-03-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0033_add_ordering_on_respondent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ('-created_at',), 'verbose_name': 'Response', 'verbose_name_plural': 'Responses'},
        ),
    ]
