# Generated by Django 3.0.3 on 2020-03-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0034_survey_allow_respondent_datasets'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='allow_respondent_entities',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='If Yes, respondents will be able to add their own entities.', verbose_name='allow respondent entities'),
        ),
    ]
