# Generated by Django 3.0.3 on 2020-03-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0035_survey_allow_respondent_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='allow_respondent_storages',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='If Yes, respondents will be able to add their own storages.', verbose_name='allow respondent storages'),
        ),
    ]
