# Generated by Django 3.0.3 on 2020-03-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0035_update_survey_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasettopicreceived',
            name='dataset_response',
        ),
        migrations.RemoveField(
            model_name='datasettopicreceived',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='datasettopicreceived',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='datasettopicresponse',
            name='dataset_response',
        ),
        migrations.RemoveField(
            model_name='datasettopicresponse',
            name='percieved_owner',
        ),
        migrations.RemoveField(
            model_name='datasettopicresponse',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='datasettopicshared',
            name='dataset_response',
        ),
        migrations.RemoveField(
            model_name='datasettopicshared',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='datasettopicshared',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='datasettopicstorageaccess',
            name='access',
        ),
        migrations.RemoveField(
            model_name='datasettopicstorageaccess',
            name='response',
        ),
        migrations.RemoveField(
            model_name='datasettopicstorageaccess',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='questionresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionresponse',
            name='response',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='hierarchy',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='response',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='response',
            name='respondent',
        ),
        migrations.RemoveField(
            model_name='response',
            name='survey',
        ),
        migrations.AlterField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='dataflowhierarchy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='dataflowhierarchy',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='datasetaccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='datasetaccess',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='datasetfrequency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='datasetfrequency',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='datasetstorage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='datasetstorage',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='question',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='role',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.DeleteModel(
            name='DatasetResponse',
        ),
        migrations.DeleteModel(
            name='DatasetTopicReceived',
        ),
        migrations.DeleteModel(
            name='DatasetTopicResponse',
        ),
        migrations.DeleteModel(
            name='DatasetTopicShared',
        ),
        migrations.DeleteModel(
            name='DatasetTopicStorageAccess',
        ),
        migrations.DeleteModel(
            name='QuestionResponse',
        ),
        migrations.DeleteModel(
            name='Respondent',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
