# Generated by Django 3.0.3 on 2020-03-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0036_survey_allow_respondent_storages'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='closing_text',
            field=models.TextField(blank=True, default='', help_text='What text do you want to appear when a respondent ends the survey?', verbose_name='closing text'),
        ),
        migrations.AddField(
            model_name='survey',
            name='introduction_text',
            field=models.TextField(blank=True, default='', help_text='What text do you want to appear when a respondent begins the survey?', verbose_name='introduction text'),
        ),
    ]
