# Generated by Django 3.0.3 on 2020-03-12 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_auto_20200311_2125'),
        ('surveys', '0036_auto_20200311_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='HierarchyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_hierarchy_levels', related_query_name='created_hierarchy_level', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='surveys.HierarchyLevel', verbose_name='parent')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_levels', related_query_name='hierarchy_level', to='projects.Project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'Hierarchy Level',
                'verbose_name_plural': 'Hierarchy Levels',
            },
        ),
        migrations.AddField(
            model_name='dataflowhierarchy',
            name='hierarchy_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hierarchies', related_query_name='hierarchy', to='surveys.HierarchyLevel'),
        ),
    ]
