# Generated by Django 3.0.3 on 2020-03-12 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0036_auto_20200312_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', related_query_name='question', to='surveys.QuestionGroup', verbose_name='group'),
        ),
    ]
