# Generated by Django 3.0.3 on 2020-03-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0037_auto_20200305_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='closing_text',
            field=models.TextField(default='', help_text='What text do you want to appear when a respondent ends the survey?', verbose_name='closing text'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='introduction_text',
            field=models.TextField(default='', help_text='What text do you want to appear when a respondent begins the survey?', verbose_name='introduction text'),
        ),
    ]
