# Generated by Django 3.0.3 on 2020-03-11 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0038_auto_20200310_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', related_query_name='entity', to='surveys.Survey', verbose_name='survey'),
        ),
    ]
