# Generated by Django 3.0.3 on 2020-03-17 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0038_add_survey_genders'),
        ('surveys', '0037_auto_20200312_1120'),
    ]

    operations = [
    ]
