# Generated by Django 3.0.3 on 2020-03-17 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0040_survey_allow_respondent_hierarchy_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='default_hierarchy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_hierarchies', related_query_name='default_hierarchy', to='surveys.DataflowHierarchy', verbose_name='default hierarchy'),
        ),
    ]
