# Generated by Django 3.0.3 on 2020-03-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0041_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='logo',
        ),
        migrations.AddField(
            model_name='logo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='surveys/logos', verbose_name='image'),
        ),
    ]
