# Generated by Django 3.0.3 on 2020-03-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0042_auto_20200317_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
    ]
