# Generated by Django 3.0.3 on 2020-03-11 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0042_auto_20200311_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetstorage',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_survey_dataset_storages', related_query_name='created_survey_dataset_storage', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
    ]
