# Generated by Django 3.0.3 on 2020-03-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0043_datasetstorage_creator'),
        ('surveys', '0034_add_response_ordering'),
    ]

    operations = [
    ]
