# Generated by Django 3.0.3 on 2020-03-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0044_auto_20200317_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='login_required',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text="If no, they won't be able to save and return to their responses, or view previous responses.", verbose_name='login required'),
        ),
    ]
