# Generated by Django 3.0.3 on 2020-03-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0046_alter_allow_respondent_datasets_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, help_text='Is published', verbose_name='is active'),
        ),
    ]
