# Generated by Django 3.0.3 on 2020-03-18 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0047_alter_is_active_default_to_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='hierarchy_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', related_query_name='role', to='surveys.HierarchyLevel', verbose_name='hierarchy level'),
        ),
    ]
