# Generated by Django 3.0.3 on 2020-03-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0048_add_field_hierachy_level_to_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='hierarchy',
        ),
    ]
