# Generated by Django 3.0.3 on 2020-03-18 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0049_remove_field_hierachy_from_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='hierarchy_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', related_query_name='entity', to='surveys.HierarchyLevel', verbose_name='hierarchy level'),
        ),
    ]
