# Generated by Django 3.0.3 on 2020-03-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0052_add_fields_to_allow_to_collect_respondent_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='invitation_required',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='If no, anyone with the survey link can respond to it.', verbose_name='invitation required'),
        ),
    ]
