# Generated by Django 3.0.3 on 2020-03-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0056_remove_field_default_hierarchy_from_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('integer', 'integer'), ('decimal', 'decimal'), ('text', 'text')], max_length=50, verbose_name='type'),
        ),
    ]
