# Generated by Django 3.0.3 on 2020-03-20 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0057_alter_field_type_on_question_to_use_simple_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='group',
        ),
    ]
