# Generated by Django 3.0.3 on 2020-03-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0058_remove_field_group_from_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='code',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='code'),
        ),
    ]
