# Generated by Django 3.0.3 on 2020-03-17 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20200312_1001'),
        ('organizations', '0003_auto_20200311_2125'),
    ]

    operations = [
    ]
